services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!12345
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: db_init_container
    depends_on:
      - sqlserver
    volumes:
      - ./db-init:/scripts
      - sql_data:/var/opt/mssql 
    entrypoint: |
      /bin/bash -c "
      if [ ! -f /var/opt/mssql/.db_initialized ]; then
        sleep 15 &&
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Password!12345 -i /scripts/script.sql &&
        touch /var/opt/mssql/.db_initialized
      else
        echo 'Database already initialized'
      fi
      "

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: backend_container
    working_dir: /app
    volumes:
      - ./Backend:/app
    ports:
      - "5000:8080"
      - "5001:5001"
    depends_on:
      - sqlserver
    command: ["dotnet", "BlogTecnicaAPI.dll"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  sql_data:
